import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import NavigationMenuComp from "@/components/NavigationMenuComp";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-rows-[100px_1fr] h-screen m-0 p-0`}      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange    >
          <NavigationMenuComp className={'border flex justify-between p-1 m-3 items-center '} />
          <main className="p-4 border m-3 ">

            {children}

          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
